name: Android APK Build

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-apk:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: 3.10

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y build-essential python3-pip git zip
        pip install buildozer

    - name: Build APK
      run: |
        sudo apt install -y libffi-dev libssl-dev
        buildozer android debug
        ls bin/

    - name: Upload APK artifact
      uses: actions/upload-artifact@v3
      with:
        name: MyApp-debug.apk
        path: bin/*.apk
