name: Android APK Build

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-apk:
    runs-on: ubuntu-latest

    env:
      ACTIONS_STEP_DEBUG: true  # Enable debug logging

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y build-essential python3-pip git zip libffi-dev libssl-dev wget unzip openjdk-8-jdk

    - name: Install Android SDK Command-Line Tools
      run: |
        mkdir -p $HOME/Android/Sdk/cmdline-tools

        # Download and extract SDK tools into 'cmdline-tools'
        wget https://dl.google.com/android/repository/commandlinetools-linux-8512546_latest.zip -O android-sdk-tools.zip
        unzip android-sdk-tools.zip -d $HOME/Android/Sdk/cmdline-tools/

        # Rename extracted 'cmdline-tools' directory to 'latest' for compatibility
        mv $HOME/Android/Sdk/cmdline-tools/cmdline-tools $HOME/Android/Sdk/cmdline-tools/latest

        # Set environment variables for Android SDK
        echo "ANDROID_HOME=$HOME/Android/Sdk" >> $GITHUB_ENV
        echo "PATH=$PATH:$HOME/Android/Sdk/cmdline-tools/latest/bin:$HOME/Android/Sdk/platform-tools" >> $GITHUB_ENV

        # Accept licenses and install required SDK components
        yes | $HOME/Android/Sdk/cmdline-tools/latest/bin/sdkmanager --licenses || true
        $HOME/Android/Sdk/cmdline-tools/latest/bin/sdkmanager "platform-tools" "build-tools;36.0.0-rc1" "platforms;android-30"

    - name: Install Python dependencies
      run: |
        pip install --upgrade pip
        pip install buildozer cython

    - name: Ensure buildozer.spec exists
      run: |
        if [ ! -f buildozer.spec ]; then
          echo "No buildozer.spec found. Please generate it with 'buildozer init'."
          exit 1
        fi

    - name: Build APK
      run: |
        buildozer android debug
        ls bin/

    - name: Upload APK artifact
      uses: actions/upload-artifact@v3
      with:
        name: MyApp-debug.apk
        path: bin/*.apk